language: elixir
elixir:
  - 1.6.4
otp_release:
  - 20

script:
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix test
  - MIX_ENV=test mix dogma
  - MIX_ENV=test mix credo --strict
after_script:
  - MIX_ENV=test mix coveralls.travis

dist: trusty
sudo: required
