language: elixir
elixir:
  - 1.7.2
otp_release:
  - 21.0

script:
  - MIX_ENV=test mix deps.get
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis

dist: trusty
sudo: required
